### ISSUE TITLE
Mailing list doesn't exist

### ISSUE THREAD

**Issue by gregid** [SANSA-Stack/Archived-SANSA-Stack#5]
I tried accessing link from the website to the mailling list:
https://groups.google.com/forum/#!forum/sansa-stack

But according to google groups the list doesn't exist.

Where can I ask questions regarding SANSA-Stack?

**Comment by GezimSejdiu** [comment]
Hi @gregid ,

many thanks for posting here. The list does exist but I guess, you may need to send a subscription request first in order to be able to post there.
We mention it somewhere on the [SANSA website](http://sansa-stack.net/): 

>**Mailing List**. Subscribe to the mailing list via @SANSA-Stack or by sending an e-mail message to sansa-stack+subscribe@googlegroups.com. Once the subscription was confirmed, you can send questions to sansa-stack@googlegroups.com.

Please, do let me know if you are still facing the issue of seeing the mailing list.

Best regards,

**Comment by gregid** [comment]
Thank you, I've now successfully subscribed.

Is the group hidden/invisible by design or just some google groups fluke?

**Comment by GezimSejdiu** [comment]
Great! 

Um, what do you mean by hidden/invisible? That the user has to subscribe first in order to post there, or a widget integration on the site?

If the former, google groups policies are designed in that way that everyone should be subscribed to the group in order to be able to post there. I think that is by default. 

If everything is working fine, please feel free to close the issue :) 

Best regards,

**Comment by gregid** [comment]
I mean when you search for groups in googlegroups doesn't recognize its existence. Some groups you can read posts/search on the google groups site but need to subscribe to post - it helps with increasing visibility of the project. At the moment the archive is not public.

I am fine if it is by design, just wanted to make sure it's not by accident.

**Comment by GezimSejdiu** [comment]
Right, good point. We will discuss this and see if there is a possibility to make the archive publicly available. Indeed, it increases the visibility of the project.

Many thanks for the suggestion.

**Comment by JensLehmann** [comment]
I made it publicly visible.

I suspect this has to do with changes at Google. At least I see a message "Group settings have been updated. If you are experiencing issues, check the FAQ for help." when managing the group and the FAQ at https://support.google.com/a/answer/9325317 item "People can’t access my group, even with a link" is exactly the issue here.

I'm closing the issue - please re-open if there are still problems.
